# Generated by Django 2.1.5 on 2019-01-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, unique=True)),
                ('p_alias', models.CharField(default='还没想好', max_length=20, null=True)),
                ('p_num', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='a_load',
        ),
        migrations.AddField(
            model_name='article',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='user.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_del',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='a_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='a_tag',
            field=models.CharField(default='Django', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='p',
            field=models.ManyToManyField(related_name='part', to='article.Article'),
        ),
    ]
